// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SetProtectionMode(arg1) {
  return window['go']['main']['App']['SetProtectionMode'](arg1);
}

export function StartPairing() {
  return window['go']['main']['App']['StartPairing']();
}
