// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetStatus():Promise<main.Status>;

export function SetProtectionMode(arg1:boolean):Promise<main.Status>;

export function StartPairing():Promise<main.Status>;
